platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

source "https://github.com/CocoaPods/Specs.git"

target 'Mall' do

	pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'ObjectMapper'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'MJRefresh'
  pod 'SVProgressHUD'


  target 'MallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MallUITests' do
    # Pods for testing
  end

end

# 第三方框架 deployment target  警告的问题
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f <= 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
