platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

source "https://github.com/CocoaPods/Specs.git"

target 'Mall' do

	pod 'Moya'
  #pod 'Moya/RxSwift'
  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'ObjectMapper'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'MJRefresh'
  pod 'SVProgressHUD'
  pod "CTMediator"


  target 'MallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MallUITests' do
    # Pods for testing
  end

end

# 第三方框架 deployment target  警告的问题
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f <= 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end


# RxDataSources UITableView: https://www.jianshu.com/p/b11f34ce478d
# RxDataSources UICollectionView: https://www.jianshu.com/p/8b9cb8d57edd
# wkwebview适配深色模式：https://www.cnblogs.com/xujiahui/p/11583710.html
# Swift 5 Result: https://www.jianshu.com/p/78ad789577df
# Moya 协议封装CTMediator: https://www.jianshu.com/p/3d6bb5a2c847
